import Header from "../components/Header";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const session = true;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {session ? (
          <div>
            <div className="sticky top-0 bg-[#ffffff]">
              <Header />
            </div>
            <div>{children}</div>
          </div>
        ) : (
          <div>
            <h1>Login page</h1>
          </div>
        )}
      </body>
    </html>
  );
}
